### ISSUE TITLE
issue 使用範例

### ISSUE THREAD

**Issue by lichin-lin** [poopoomarvin/Blokus#1]
# 嗨我是一個issue
## 覺得哪邊不好都可以打在這裡

> 混蛋 變數看不懂
- 記得不要底線🌊
- 或是命名聽不懂⚡️

**Comment by lichin-lin** [comment]
下面可以回話
咦是亮忘記了 或是我白癡了
就提說

# 我來修改

**Comment by tyhsu** [comment]
來試試看task list～～ˊˇˋ
- [x] 函數盡量打個註解，名字盡量取容易理解、和功用相符的
- [x] 變數是大寫派喔❤️
- [x] private和public要分清楚，不能隨意更動的請用private

**Comment by lichin-lin** [comment]
棒棒 我還沒用過todo list
對了變數要不要再說清楚一點
1. class name
2. function name
3. 變數

讓我永生難忘

**Comment by nivram108** [comment]
喔喔喔好酷喔
-  ler
- lerrr
- 兔子

**Comment by lichin-lin** [comment]
三小ＸＤ

# 素質

**Comment by tyhsu** [comment]
- 變數：variableName
- 函數：functionName
- class：ClassName
