### ISSUE TITLE
Need to fix or add

### ISSUE THREAD

**Issue by tyhsu** [poopoomarvin/Blokus#2]
**game.cpp**
- [x] 24: 開頭註解block的意思
- [x] shapesA和shapesB是不需要的？
- [x] firstStepFlagA和firstStepFlagB可以改成bool
## 

p.s 有改名字的變數們：

**game.cpp**
- first_step_flag_A => firstStepFlagA
- first_step_flag_B => firstStepFlagB
- pieces_A => piecesUseA
- pieces_B => piecesUseB
- pieces_pointer => piecesUsePointer
- printMap() => printBoard()
- checkindex() => checkShapeID()
- checkgame() => isGameEnd()
- checkgameClear() => isGameEndAI()
- checkpieces() => hasPlaceToPut()

**play.cpp**
- command() => twoPlayers()
- PK() => playerAI()

**ai.cpp**
- autoGame() => twoAIs()

**Comment by nivram108** [comment]
Done
